# network-policy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-outbound
spec:
  podSelector:
    matchLabels:
      app: dibank-transaction-service
  policyTypes:
    - Egress
  egress:
    - {}