apiVersion: v1
kind: Service
metadata:
  name: dibank-notification-service
spec:
  type: NodePort
  selector:
    app: dibank-notification-service
  ports:
    - protocol: TCP
      port: 8105
      targetPort: 8105
      nodePort: 30105

