apiVersion: v1
kind: Service
metadata:
  name: dibank-auth-service
  namespace: default
  labels:
    app: dibank-auth-service
    group: dibank
spec:
  type: ClusterIP
  ports:
    - port: 8104
      targetPort: 8104
#      nodePort: 30104
#      protocol: TCP
  selector:
    app: dibank-auth-service
    group: dibank