apiVersion: apps/v1
kind: Deployment
metadata:
  name: dibank-account-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dibank-account-service
      group: dibank
  template:
    metadata:
      labels:
        app: dibank-account-service
        group: dibank
    spec:
      containers:
        - name: dibank-account-service
          image: dibank-account-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8101
          env:
            - name: CONTAINER_NAME
              value: "dibank-banking-integration"
            - name: VIETQR_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: vietqr-secrets
                  key: client-id
            - name: VIETQR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: vietqr-secrets
                  key: api-key
            - name: VIETQR_URL_GEN_QR
              valueFrom:
                configMapKeyRef:
                  name: vietqr-config
                  key: url-gen-qr